server:
  port: 8081

## Default connection pool
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dev}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    schemas: products
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dev}
    
